{% set version = "3.50.1" %}
{% set year = "2025" %}
{% set version_split = version.split(".") %}
{% set major = version_split[0] %}
{% set minor = version_split[1]|int * 10 %}
{% set bugfix = version_split[2]|int * 100 %}
{% set version_coded=(major ~ (("%03d" % minor)|string) ~ (("%03d" % bugfix)|string)) %}

package:
  name: sqlite-tools
  version: {{ version }}

source:
  url: https://www.sqlite.org/{{ year }}/sqlite-src-{{ version_coded }}.zip
  sha256: 9090597773c60a49caebb3c1ac57db626fac4d97cb51890815a8b529a4d9c3dc

build:
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - make  # [not win]
    - tk
  host:
    - libsqlite >={{ version }}  # [not win]
    - zlib                       # [not win]
    - tk

outputs:
  - name: sqldiff
    files:
      - bin/sqldiff              # [unix]
      - Library\bin\sqldiff.exe  # [win]
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ stdlib("c") }}
        - make  # [not win]
      host:
        - libsqlite >={{ version }}  # [not win]
        - zlib                       # [not win]

    test:
      commands:
        - sqldiff --help
  - name: sqlite_rsync
    files:
      - bin/sqlite3_rsync              # [unix]
      - Library\bin\sqlite3_rsync.exe  # [win]
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ stdlib("c") }}
        - make  # [not win]
      host:
        - libsqlite >={{ version }}  # [not win]
        - zlib                       # [not win]

    test:
      commands:
        - sqlite3_rsync --version
  - name: sqlite_analyzer
    files:
      - bin/sqlite3_analyze              # [unix]
      - Library\bin\sqlite3_analyze.exe  # [win]
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ stdlib("c") }}
        - make  # [not win]
        - tk
      host:
        - libsqlite >={{ version }}  # [not win]
        - zlib                       # [not win]
        - tk

    test:
      commands:
        - sqlite3_analyze --version


about:
  home: http://www.sqlite.org/
  license: Unlicense
  license_url: http://www.sqlite.org/copyright.html
  summary: Implements a self-contained, zero-configuration, SQL database engine
  description: |
    SQLite is a self-contained, high-reliability, embedded, full-featured,
    public-domain, SQL database engine.It is the most used database engine
    in the world.
  doc_url: http://www.sqlite.org/docs.html
  doc_source_url: https://github.com/mackyle/sqlite/tree/master/doc
  dev_url: https://github.com/mackyle/sqlite

extra:
  feedstock-name: sqlite-tools
  recipe-maintainers:
    - flaviomartins
